# This workflow will build the python app on release, upload it to the release page,
# and publish it to PyPI.

name: Build and Publish Release

on:
  release:
    types: [published]

jobs:
  # This job builds the source distribution and wheel.
  release-build:
    name: Build Release Distributions
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to write to the release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Use specific Python version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
        
    - name: Build release distributions
      run: python -m build

    - name: Upload distribution files to release page
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz

    - name: Store distribution files as artifact for publishing job
      uses: actions/upload-artifact@v4
      with:
        name: python-package-dists
        path: dist/

  # This job publishes the package to PyPI.
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [release-build] # This job runs only after the build job is successful
    permissions:
      id-token: write # This is required for trusted publishing
    
    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    environment:
      name: pypi
      url: https://pypi.org/p/requirements-resolver

    steps:
      - name: Retrieve release distributions from build job
        uses: actions/download-artifact@v4
        with:
          name: python-package-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1